apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kn-b-trigger
spec:
  broker: default
  filter:
    attributes:
      type: com.demo.event
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-b
  delivery:
    retry: 0