apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kn-fn
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: fn
  delivery:
    retry: 0